### PR TITLE
UMD Wrapper + Gulp build + Bower/NPM/Component Support

### PR DESCRIPTION
**Pull request by TomNeyland**
All **tests are passing**.

This **adds a ```gulp build``` task** that **wraps ```pourover.js``` in a [UMD](https://github.com/umdjs/umd)**. 
The result is written to ```dist/pourover.js```.
A minified version is written to ```dist/pourover.min.js```.

Gulp related dependencies are managed by npm, installed via ```npm install```. 
Testing dependencies are now managed by bower's 'dev-dependencies', installed via ```bower install```. 

**Increased compatibility** was the primary motivation for this pull request, my issue was that PourOver assumes underscore is available globally as ```_```.

I am attempting to use PourOver in an environment where ```underscore``` is loaded via a module loader, and therefore it is not available globally as ```_```. Wrapping PourOver in a UMD lets it take advantage of the module loader when it is present, while **transparently falling back to the original behavior** if it is not.

### CODE REVIEW

**Comment by hhsnopek** [comment]
@TomNeyland any updates on this?

**Comment by hhsnopek** [comment]
Ping @esmooov & @TomNeyland - anything I can do to help get this merged?

**Comment by SpencerCarstens** [comment]
Any update on this?

**Comment by TomNeyland** [comment]
@esmooov @hhsnopek @SpencerCarstens @paradox41 

Fixed the merge conflicts and reran the tests and build.

**Comment by hhsnopek** [comment]
Looks good to me :+1:

**Comment by hhsnopek** [comment]
ping @esmooov - this PR now includes: npm, bower, component and web support, updated tests to mocha, ability to have running tests on Travis, and is already version bumped.

**Comment by TomNeyland** [comment]
@esmooov any update on this?
@hhsnopek

**Comment by hhsnopek** [comment]
@TomNeyland Hey the community version of Pourover is now here: [hhsnopek/pourover](//github.com/hhsnopek/pourover)

**Comment by tiffehr** [comment]
Hey, taking over this repo (with teammates) after @esmooov's departure from NYT.  I'll be reviewing this and merging once I get things figured out.

**Comment by tiffehr** [comment]
Closing in favor of us doing some updates to help with documentation, exploration and our own use-cases, but also making sure the community-supported version has a lot of autonomy.

**Pull request closed without merging**
