### PR TITLE
Enables use as NPM require, relative path

### PR DESCRIPTION
**Pull request by solsson**
like `var PourOver = require('./pourover')` until a full npm module is made

### CODE REVIEW

**Comment by notduncansmith** [comment]
+1

**Comment by hhsnopek** [comment]
Hey guys, see #47 - this is waiting for review and merge but contains what you're looking for

**Comment by tiffehr** [comment]
@hhsnopek's community fork better addresses NPM support, along with related supporting changes.

**Comment by hhsnopek** [comment]
already available - https://www.npmjs.com/package/pourover

**Comment by solsson** [comment]
Well resolved. Thanks.

**Pull request closed without merging**
